Repository manga-download/hakuneko, pull requests merged in 2020-07, with the labels that each got.

#2039 [JapanRead] Implimented new method and Fixed the URI naming error
  src/web/mjs/connectors/JapanRead.mjs
Labels: Website Change

#2038 FEAT-MagicScrollv2 improvement and auto next chapter
  src/web/lib/hakuneko/frontend@classic-dark/pages.html
  src/web/lib/hakuneko/frontend@classic-light/pages.html
Labels: Enhancement

#2068 [MangaHost] dom selector change
  src/web/mjs/connectors/MangaHost.mjs
Labels: Website Change

#2090 AutoNextChapter pixel-perfect sensitivity
  src/web/lib/hakuneko/frontend@classic-dark/pages.html
  src/web/lib/hakuneko/frontend@classic-light/pages.html
Labels: Bug
